### ISSUE TITLE
Looping

### ISSUE THREAD

**Issue by terenzeyuen** [marcuseckert/Squall#7] opened 2016-08-01 12:01 UTC
Hi, great tool – just reviewing the features but having a slight issue to loop. This is the code, any ideas? It only plays once.

```
let animation = SLSquallAnimation(fromBundle: "animation.sqa")
        loadingView.layer.addSublayer(animation!)
        animation?.playbackType = .Loop
        animation?.play()
```

**Comment by marcuseckert** [comment] 2016-08-11 11:39
It's a bug where you have to set the onAnimationEvent callback. If it's not set, it won't loop. So for now you'll have to add an empty block/closure for that to make it work. I'll fix it for the next release

**Comment by iain-reid** [comment] 2017-01-17 16:12
I've run into the same issue - however the loop is still not working or some reason, even after adding the onAnimationEvent callback. I'm using an SLSquallAnimation - when I change to an SLCoreAnimation it works...

Any help would be appreciated @marcuseckert
 
    [self.coachArrowsView.layer addSublayer:self.coachArrowsAnimation];
    
    self.coachArrowsAnimation.playbackType = SLPlaybackTypeLoop;
    
    [self.coachArrowsAnimation setOnAnimationEvent:^(SLAnimationEvent animationEvent) {
        
    }];

    [self.coachArrowsAnimation play];

**Comment by marcuseckert** [comment] 2017-01-17 16:51
You should no longer need the empty block, this issue has been fixed. But do you have a valid license set? Also you could try logging the time in the onAnimationEvent block?
self.coachArrowsAnimation.onAnimationEvent = ^(SLAnimationEvent e) {
        NSLog(@"time %f", self.coachArrowsAnimation.time);
    };
(this has a retain cycle but it's for debugging only)

**Comment by iain-reid** [comment] 2017-01-18 10:15
Hey @marcuseckert - Yup, we have a valid license key (set in App Delegate) - We changed the animation from SLSqallAnimation to SLCoreAnimation and the looping works... I'll give what you suggest a try also and report back :-)

**Comment by marcuseckert** [comment] 2017-01-18 12:29
that's good to hear! But could you send me the animation that's not working? Does it not work with any animation or is it just this one? When I test it it seems to work as expected but maybe there's some case that breaks it.

**Comment by iain-reid** [comment] 2017-01-24 15:57
Hey @marcuseckert , I've attached the animation that isn't working - however all of our animations do the same thing when 'SLPlaybackTypeLoop' is set - they play once, return to the first frame and stop. I've also tried using the callback block (SLAnimationEventEnd) to set the time back to 0, then play again - and this has the same effect. Pretty weird. 

We are using the Pod version of this library - I assume it's the most up to date.

[onboarding-B.sqa.zip](https://github.com/marcuseckert/Squall/files/727162/onboarding-B.sqa.zip)

**Comment by ninjudd** [comment] 2017-01-28 01:21
This isn't working for me either. Did you ever figure out a fix?

**Comment by marcuseckert** [comment] 2017-01-28 08:25
@deeplightco I've tried it now but can't reproduce it:/ I made a clean project and downloaded the pod but it loops as expected...
@ninjudd does no animation loop for you or is it just one? Have you tried setting up a clean project and does it work there? 
I'm wondering if it only happens under load and possibly screws up the timing somewhere...

**Comment by ninjudd** [comment] 2017-01-28 14:01
It only happens with SLSquallAnimation. Switching to SLCoreAnimation
fixes it.

**Comment by iain-reid** [comment] 2017-01-30 09:31
Hey @marcuseckert I've tried with multiple animations and looping only seems to work on SLCoreAnimation - can you share a snippet or the clean project file so we can try it at this end?

**Comment by marcuseckert** [comment] 2017-01-30 11:16
hey, so it's just a matter of setting up a new project, adding Squall and using this
SLSquallAnimation* a = [SLSquallAnimation animationFromBundle:@"onboarding-B.sqa"];
[self.view.layer addSublayer:a];
a.frame = self.view.frame;
a.playbackType = SLPlaybackTypeLoop;
[a play];
I've tried it with both the cocoapods framework and the version from the website and it loops fine:/ So, not sure what's happening

**Comment by iain-reid** [comment] 2017-01-30 13:05
@marcuseckert Yeah - doing it the same way as you suggest in our current project and it doesn't work for me (plays to end then blank). 

Tried a fresh project w/ Cocoapods - pasted the above snippet into -viewDidAppear, and the animation doesn't complete (plays 1-2s then blank) which is also very weird...

```
-(void)viewDidAppear:(BOOL)animated{
    [super viewDidAppear:animated];

    SLSquallAnimation* a = [SLSquallAnimation animationFromBundle:@"onboarding-B.sqa"];
    [self.view.layer addSublayer:a];
    a.frame = self.view.frame;
    a.playbackType = SLPlaybackTypeLoop;
    [a play];
}

```

**Comment by marcuseckert** [comment] 2017-01-30 13:14
@deeplightco did you have the license added? Can you try the project without Cocoapods and just add the framework from the website (http://www.marcuseckert.com/squall/downloads/squall-2.02-Mac.zip)?

**Comment by iain-reid** [comment] 2017-01-30 16:17
@marcuseckert - Nope :-p - But I've added license now and same problem as originally (play to end then blank). Tried adding the Squall Framework manually via the D/L link you sent - same issue.

I'm using iOS 10.2, Xcode 8.2.1 and CocoaPods 1.1.1

**Comment by marcuseckert** [comment] 2017-02-09 18:24
@deeplightco @ninjudd I've found the error. It was only happening on the device but I only tested on the sim which is why I never saw it. It'll be fixed in the next version, meanwhile you can use:
https://www.dropbox.com/s/mpnhc2xeowd227v/Squall.framework.zip?dl=0  
Should work!

**Closed as completed** 2017-04-01 21:43 UTC
